### PR TITLE
Upload CryptoStrikers Icon 2

### PR DESCRIPTION
**Pull request by Chagz19**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by vikmeup** [comment]
@Chagz19 image should be a squre and 256by256

**Comment by Chagz19** [comment]
It has been changed, please verify.

**Comment by kolya182** [comment]
@Chagz19 Doesn't look like 256x256
screenshot 2018-07-09 17 14 20

**Comment by Chagz19** [comment]
My bad, I didn't save the file after modifying it. Please check again. Thanks.

**Comment by vikmeup** [comment]
@Chagz19 there is a conflict in files.

**Comment by kolya182** [comment]
@Chagz19 Added here https://github.com/TrustWallet/tokens/commit/2bf108a4297f95dadc7ffd36af0d25b95d8b3262

**Pull request closed without merging**
