### PR TITLE
update Bitsifu Logo

### PR DESCRIPTION
**Pull request by ethAITOKEN**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by vikmeup** [comment]
@ethAITOKEN can you change format of `0x448a47359833b26e5aa988ddb7a72099f6242170.jpg` to `png`?

**Comment by ethAITOKEN** [comment]
There was a mistake

**Comment by ethAITOKEN** [comment]
0x448a47359833b26e5aa988ddb7a72099f6242170 is the old contract
0x62bf50192b3ef428e24Bc8d10f0c2A6Eabe80E08 is the new address i want to update now!

**Comment by ethAITOKEN** [comment]
This is for a different token. do i need to crate a new pull for this address?

**Comment by vikmeup** [comment]
@ethAITOKEN can you lowercase `0x62bf50192b3ef428e24Bc8d10f0c2A6Eabe80E08.png` and you are good to go

**Comment by kolya182** [comment]
@ethAITOKEN Added it here for you https://github.com/TrustWallet/tokens/commit/174ab86257654fb9dfbd6762e68fec01863a36fc
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwalletapp.com/logo-assets). Tokens will show up automatically once the user receives them.
Feel free to share this on social media and tag Trust Wallet:
 Twitter: @trustwalletapp 
Facebook: @trustwalletapp

**Pull request closed without merging**
