### PR TITLE
coin by insomnia

### PR DESCRIPTION
**Pull request by Ins0mniaIco**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by vikmeup** [comment]
@Ins0mniaIco can you lowercase the name and you should be good to go!

**Comment by Ins0mniaIco** [comment]
Updated

**Comment by kolya182** [comment]
@Ins0mniaIco Still one of them in uppercase !

**Comment by Ins0mniaIco** [comment]
Try that, didn't see any uppercase, but could be the : that was translated as uppercase?

**Comment by kolya182** [comment]
@Ins0mniaIco No worries, i have added them here https://github.com/TrustWallet/tokens/commit/2b4be4a19d5a9e78ad9ab6777d04ba365a659b98 
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwalletapp.com/logo-assets). Tokens will show up automatically once the user receives them.
Feel free to share this on social media and tag Trust Wallet:
 Twitter: @trustwalletapp 
Facebook: @trustwalletapp

**Pull request closed without merging**
