### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by artictypsrsx**
cropped-dropil-logo-2
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [ ] Filename in the `lowercase` format
- [ ] Image format: `png`
- [ ] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by artictypsrsx** [comment]
how do i resize?

**Comment by vikmeup** [comment]
@artictypsrsx what's the smart contract address? I will do it for you

**Comment by vikmeup** [comment]
@artictypsrsx for each token

**Comment by artictypsrsx** [comment]
0x4672bad527107471cb5067a887f4656d585a8a31

or etherscan https://etherscan.io/token/0x4672bad527107471cb5067a887f4656d585a8a31

**Comment by artictypsrsx** [comment]
1WO
0xfdbc1adc26f0f8f8606a5d63b7d3a3cd21c22b23
--
https://etherscan.io/token/0xfdbc1adc26f0f8f8606a5d63b7d3a3cd21c22b23 

ZCO

0x2008e3057bd734e10ad13c9eae45ff132abc1722
--
https://etherscan.io/token/0x2008e3057bd734e10ad13c9eae45ff132abc1722

CHX

0x1460a58096d80a50a2f1f956dda497611fa4f165
--

https://etherscan.io/token/0x1460a58096d80a50a2f1f956dda497611fa4f165

FNTB

0xbd4b60a138b3fce3584ea01f50c0908c18f9677a
--
https://etherscan.io/token/0xbd4b60a138b3fce3584ea01f50c0908c18f9677a

**Comment by artictypsrsx** [comment]
THX!

**Comment by vikmeup** [comment]
Nice! Added token images for all of them! Thank you!

**Comment by artictypsrsx** [comment]
Appreciate it!

Sent from my iPhone
Joe


On Apr 29, 2018, at 5:38 AM, Viktor Radchenko <notifications@github.com<mailto:notifications@github.com>> wrote:


Nice! Added token images for all of them! Thank you!

**Comment by artictypsrsx** [comment]
[cid:b365d8aa-299c-4518-a710-cb0eff02ffd6@namprd17.prod.outlook.com]



[cid:a120e495-0a0a-4fec-a50b-d7bfc4b08424@namprd17.prod.outlook.com]



[cid:ab1e148e-d58f-44ac-a3ac-a99bbeecf103@namprd17.prod.outlook.com]


Sent from my iPhone
Joe
2672210932

**Comment by artictypsrsx** [comment]
Yup, found you. I’m @artictypsrsx

Sent from my iPhone
Joe
2672210932

On Apr 30, 2018, at 7:19 PM, Viktor Radchenko <notifications@github.com<mailto:notifications@github.com>> wrote:


can you dm on me telegram: vikmeup?

**Pull request closed without merging**
