### PR TITLE
Added Bitcoin Token (BTK)

### PR DESCRIPTION
**Pull request by bitcoin-token**
Token Name: BitcoinToken
Token Symbol: BTK
Token Decimal: 18
Tokens in Circulation: 10,000,000,000
Contract Address: 0xdb8646f5b487b5dd979fac618350e85018f557d4

### CODE REVIEW

**Comment by vikmeup** [comment]
@bitcoin-token can you tell me more about the token, what's the use case for it?

**Comment by bitcoin-token** [comment]
@vikmeup our goal is large user adoption and ecommerce application. We are in talks with some large apps to airdrop to all their users and are in talks with ecommerce integration solutions. Our goal price range is $1 area or less making it more user-friendly then fractions of a currency to pay for small transactions. A big focus is de-centralization as many currencies are centralized and businesses rather then a Bitcoin type of currency where its in the hands of the people.  Our community has been requesting Trust Wallet and would be excited for the addition.

**Comment by vikmeup** [comment]
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwalletapp.com/logo-assets). Tokens will show up automatically once the user receives them.

Feel free to share this on social media and tag Trust Wallet:
Twitter: @TrustWalletApp
Facebook: @TrustWalletApp

**Comment by bitcoin-token** [comment]
https://twitter.com/bitcoin_token/status/980097866227245059   we will continue to share with our wider community! Thanks.

**Pull request merged**
