### PR TITLE
Add NAC token

### PR DESCRIPTION
**Pull request by ducntq**

### CODE REVIEW

**Comment by vikmeup** [comment]
Can you lowercase the name?

**Comment by ducntq** [comment]
Hey @vikmeup, I've just updated new version without text.

**Comment by ducntq** [comment]
Somehow git is not picking up the new file name. I'm gonna open a new PR.

**Comment by vikmeup** [comment]
@ducntq oh, I have those issues sometimes. Use this: https://git-scm.com/docs/git-mv

**Pull request closed without merging**
