### PR TITLE
Upload SmartCoin

### PR DESCRIPTION
**Pull request by ReinoGroup**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by ReinoGroup** [comment]
The SmartCoin logo was not up yet , please advise

**Comment by vikmeup** [comment]
delete this file:  images/smartcoin.jpg

**Comment by ReinoGroup** [comment]
Ca you help me to delete ? I can't find the delete button

**Comment by ReinoGroup** [comment]
Ca you help me to delete ? I can't find the delete button

**Pull request closed without merging**
