### PR TITLE
Reuploading El Rey updated Logo

### PR DESCRIPTION
**Pull request by Donzina**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by Donzina** [comment]
I just updated the logo to be visible and more clearer. please merge and update

**Comment by kolya182** [comment]
Why you adding every time so many duplicates ?. Could you check address existence before push new ones ?. Thank you.

**Comment by Donzina** [comment]
The previous logo was not clear and visible so I had to reupload a better one. Kindly merge as it is correct now

**Comment by kolya182** [comment]
If it was just one, why not upload only one ?

**Comment by kolya182** [comment]
Here https://github.com/TrustWallet/tokens/commit/9486a0c8e85aa65d33833c6c15534573578e5248

**Comment by Donzina** [comment]
I uploaded just one now.

**Comment by kolya182** [comment]
Actually not, you uploaded a bunch

**Comment by Donzina** [comment]
Yes that image is just what I reuploaded

**Comment by Donzina** [comment]
Oh maybe I didn't know so you can discard the rest and I will always check before uploading.

**Pull request closed without merging**
