### PR TITLE
OMNIS-BIT

### PR DESCRIPTION
**Pull request by CryptoHuntersClub**
logoomnist
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by CryptoHuntersClub** [comment]
OMNIS-BIT is the token that brings everyone closer to the cryptocurrencies' world with its services.

**Comment by kolya182** [comment]
Is this contract address for image 0x3123ff80cbdfd35577628a41ff50598cefc2d236 ?

**Comment by CryptoHuntersClub** [comment]
Yes! Thank you!

Il giorno gio 14 mar 2019 alle 8:11 PM Mykola <notifications@github.com> ha
scritto:

**Comment by kolya182** [comment]
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwallet.com/logo-assets). Tokens will show up automatically once the user receives them.
Feel free to share this on social media and tag Trust Wallet:
 Twitter: @trustwalletapp 
Facebook: @trustwalletapp

**Pull request merged**
