### PR TITLE
Upload TXC

### PR DESCRIPTION
**Pull request by Jeff080808**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by vikmeup** [comment]
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwalletapp.com/logo-assets). Tokens will show up automatically once the user receives them.

Feel free to share this on social media and tag Trust Wallet:
Twitter: @TrustWalletApp
Facebook: @TrustWalletApp

**Comment by Jeff080808** [comment]
> Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwalletapp.com/logo-assets). Tokens will show up automatically once the user receives them.
> 
> Feel free to share this on social media and tag Trust Wallet:
> Twitter: @TrustWalletApp
> Facebook: @TrustWalletApp

Hello, What do you mean by tokens willl show up once users receives them

**Comment by vikmeup** [comment]
@Jeff080808 trust parsing the whole blockchain, once it sees new token coming to the user, it will appear automatically in the list of tokens for him.

**Comment by Jeff080808** [comment]
How do i make our token searchable by just keying the symbol?

**Pull request merged**
