### PR TITLE
SELF TOKEN icon update

### PR DESCRIPTION
**Pull request by jasongxpv**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by kolya182** [comment]
Added here https://github.com/TrustWallet/tokens/commit/8b4968171ee06df0a6789ff1189ac8502bc0e09b?short_path=13ccc61#diff-13ccc611b749d2e3ec62aba59b92b879

**Comment by kolya182** [comment]
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwalletapp.com/logo-assets). Tokens will show up automatically once the user receives them.
Feel free to share this on social media and tag Trust Wallet:
 Twitter: @trustwalletapp 
Facebook: @trustwalletapp

**Comment by jasongxpv** [comment]
Why I don't have see the change in my wallet?

**Comment by kolya182** [comment]
Because it uses old cached image file, wait for some time, or just reimport your wallet(s) and make sure back it up first

**Pull request closed without merging**
