### PR TITLE
Upload KartingCoins

### PR DESCRIPTION
**Pull request by billethekid**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [ ] Filename in the `lowercase` format
- [ ] Image format: `png`
- [ ] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by vikmeup** [comment]
@billethekid can you lowercase files names?

**Comment by vikmeup** [comment]
@billethekid please follow guidelines for adding a new token image.

**Comment by billethekid** [comment]
I did nr iT dont work ? 

Met vriendelijke groet, 
 
Kartbaan Winterswijk

**Comment by vikmeup** [comment]
@billethekid it had too many files with a wrong naming. Please upload only one you want to use.

or send me in telegram @vikmeup so I can do it for you quicker.

**Comment by billethekid** [comment]
I am at my business now will do it later 

Met vriendelijke groet, 
 
Kartbaan Winterswijk

**Pull request closed without merging**
