### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by cherrybomb420**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [0xf09209cC5EaE846ee2cc4a493e7B962CA7BCfbbb.png ] Filename in the `lowercase` format
- [
reallifecointoken
]
- [256 by 256 px] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by kolya182** [comment]
Please follow requirements

**Comment by cherrybomb420** [comment]
What needs to be fixed?

**Comment by kolya182** [comment]
@cherrybomb420 Everything https://github.com/TrustWallet/tokens#requirements

**Comment by cherrybomb420** [comment]
Harsh lol...working on it now, my bad..

**Pull request closed without merging**
