### PR TITLE
New coin added

### PR DESCRIPTION
**Pull request by emiliomarin**
0xfe7b915a0baa0e79f85c5553266513f7c1c03ed0

### CODE REVIEW

**Comment by vikmeup** [comment]
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwalletapp.com/logo-assets). Tokens will show up automatically once the user receives them.

Feel free to share this on social media and tag Trust Wallet:
Twitter: @TrustWalletApp
Facebook: @TrustWalletApp

**Comment by emiliomarin** [comment]
@vikmeup Thanks.
One more question, do you have also a complete list of coins listed on json format?
I was looking for data of most of the coins with contract address, name, decimals, symbol

**Comment by vikmeup** [comment]
@emiliomarin all tokens has been parsed via [trust-ray](https://github.com/TrustWallet/trust-ray) so there is no need to manage list of all the tokens/

**Comment by emiliomarin** [comment]
@vikmeup I see, thanks.
Do you have any kind of tutorial on how to implement it on my app? I added it to my heroku but i'm a bit lost

**Pull request merged**
