### PR TITLE
Upload HashBXCoin

### PR DESCRIPTION
**Pull request by Raphael0792**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [ ] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by kolya182** [comment]
Just leave selected one, remove the rest
screenshot 2018-09-18 21 36 12

**Comment by kolya182** [comment]
Added here https://github.com/TrustWallet/tokens/pull/462

**Comment by Raphael0792** [comment]
Hello,

Thank you sorry for the mistake cause. I'm a little confuse can you explain
what do i do next and how long will it take to apply on the application

2018-09-19 12:00 GMT+07:00 Mykola <notifications@github.com>:

**Comment by kolya182** [comment]
Make sure to add image to `tokens` folder

**Comment by Raphael0792** [comment]
Hello,

Im so sorry but Im quite new to this i donr have any idea how do i do it
??? and my developer team is on leave.. How do i add the image ?? and how
will i know that coin from our company is added in your wallet

2018-09-19 12:45 GMT+07:00 Mykola <notifications@github.com>:

**Comment by kolya182** [comment]
Just follow the video in repository description https://github.com/TrustWallet/tokens

**Pull request closed without merging**
