### PR TITLE
simplyBrand SBA

### PR DESCRIPTION
**Pull request by kaufmanchang**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by kolya182** [comment]
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwallet.com/logo-assets). Tokens will show up automatically once the user receives them.
Feel free to share this on social media and tag Trust Wallet:
 Twitter: @trustwalletapp 
Facebook: @trustwalletapp

**Comment by kaufmanchang** [comment]
Thanks a lot @kolya182 We indeed will do promotion to our community soon about fully compatible with Trust Wallet.

Our Designer wanna do some optimization to the image after seeing the result, how should we update the image?

thanks for the help

**Comment by kolya182** [comment]
@kolya182 You can update in the same way as you uploaded, just replace old image with new one and make another PR.

**Comment by kaufmanchang** [comment]
Thanks man! will do it now.

**Pull request merged**
