### PR TITLE
Upload YFT Token 

### PR DESCRIPTION
**Pull request by Borongli**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [ ] Filename in the `lowercase` format
- [ ] Image format: `png`
- [ ] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by vikmeup** [comment]
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwalletapp.com/logo-assets). Tokens will show up automatically once the user receives them.

Feel free to share this on social media and tag Trust Wallet:
Twitter: @TrustWalletApp
Facebook: @TrustWalletApp

**Comment by Borongli** [comment]
Hi, my token logo hasn't updated yet. What did I do wrong or what should I
do?

Thanks.

**Comment by vikmeup** [comment]
It’s cached on the client side for 7 days, new users will see logo.

**Comment by vikmeup** [comment]
@Borongli it is cached on your phone for 7 days.

**Pull request merged**
