### PR TITLE
Add Compound cTokens

### PR DESCRIPTION
**Pull request by hayesgm**
[Compound Finance](https://compound.finance) has added cTokens to its version 2 protocol (announcement here: https://medium.com/compound-finance/compound-v2-is-live-157db0b7cfc8). These tokens are already integrated into wallets such as Coinbase Mobile, and it would be great to add them to Trust Wallet. For reference, these tokens are normal ERC-20 tokens and they represent a balance in a Compound v2 market.

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by hayesgm** [comment]
For reference, here are Etherscan links for the included tokens:

* [Compound Basic Attention Token](https://etherscan.io/token/0x6c8c6b02e7b2be14d4fa6022dfd6d75921d90e4e)
* [Compound Dai](https://etherscan.io/token/0xf5dce57282a584d2746faf1593d3121fcac444dc)
* [Compound Ether](https://etherscan.io/token/0x4ddc2d193948926d02f9b1fe9e1daa0718270ed5)
* [Compound Augur](https://etherscan.io/token/0x158079ee67fce2f58472a96584a73c7ab9ac95c1)
* [Compound USD Coin](https://etherscan.io/token/0x39aa39c021dfbae8fac545936693ac917d5e7563)
* [Compound 0x](https://etherscan.io/token/0xb3319f5d18bc0d84dd1b4825dcde5d5f7266d407)

**Comment by kolya182** [comment]
@hayesgm Thanks for the links

**Comment by dappcoder** [comment]
@hayesgm "Compound Wrapped BTC" is missing from the list.

Etherscan link: https://etherscan.io/token/0xc11b1268c1a384e55c48c2391d8d480264a3a7f4

It would be nice to have cWBTC with the same styling.

**Comment by hayesgm** [comment]
@dappcoder Yes, I'll create a PR for this.

**Comment by dappcoder** [comment]
Hey @hayesgm thanks!

**Pull request merged**
