### PR TITLE
Update Contract Address of FUTURAX (FXC)

### PR DESCRIPTION
**Pull request by endofthepain**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by vikmeup** [comment]
@endofthepain lowercase filename please

**Comment by endofthepain** [comment]
https://etherscan.io/token/0xc92D6E3E64302C59d734f3292E2A13A13D7E1817 my contract like this

**Comment by vikmeup** [comment]
Committed in https://github.com/TrustWallet/tokens/commit/88a8b67f2a0817696ba522a1704cc9eaaec7312a

**Comment by vikmeup** [comment]
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwalletapp.com/logo-assets). Tokens will show up automatically once the user receives them.

Feel free to share this on social media and tag Trust Wallet:
Twitter: @TrustWalletApp
Facebook: @TrustWalletApp

**Pull request closed without merging**
