### PR TITLE
This is to updated the logo with better view

### PR DESCRIPTION
**Pull request by maycoin**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by maycoin** [comment]
To request update new fine tune logo.

**Comment by kolya182** [comment]
Images already added, what makes you add them again ?.

**Comment by maycoin** [comment]
The logo too big, it show not properly in the Trust Wallet. So, I make a smaller and upload again.

**Comment by kolya182** [comment]
I see now, updated here https://github.com/TrustWallet/tokens/commit/7db4a56b0ac86f8f0f9203651227fdfe1132c508

**Comment by maycoin** [comment]
Thank you very much

**Pull request closed without merging**
