### PR TITLE
 Add 400 new images

### PR DESCRIPTION
**Pull request by tobin123**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by kolya182** [comment]
Where did you get all of them ?

**Comment by Juddy0839** [comment]
how to add image ?

**Comment by Juddy0839** [comment]
0xa47a5e8696b47f1dd612eaad7254c4ca039

**Comment by kolya182** [comment]
@Juddy0839 You already added may images, what is your question ?

**Pull request merged**
