### PR TITLE
Upload FlingoCash

### PR DESCRIPTION
**Pull request by epic212**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by epic212** [comment]
Upload flingocash

**Comment by vikmeup** [comment]
Can you delete capitalized version? There is two files

**Comment by epic212** [comment]
Do you want me to close this request with 2 files and open new request because I don’t know how to delete one of the files. The reason I uploaded the second is because the first uploaded photo labeled as bing.bing

**Comment by epic212** [comment]
PNG.png

**Comment by vikmeup** [comment]
Yes, you can close this and open new one. Make sure to delete fork and create it again

**Comment by epic212** [comment]
I know how to close the pull the request where it says close and comment,  but how do I delete the fork?

**Comment by vikmeup** [comment]
In the settings of this fork

**Comment by kolya182** [comment]
Added here https://github.com/TrustWallet/tokens/commit/ecd41e83ddcb6e83f69b75674f39ebc517c2ab61

**Pull request closed without merging**
