### PR TITLE
Please add HighVibe.Network (HV)

### PR DESCRIPTION
**Pull request by justover**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [ ] Filename in the `lowercase` format
- [ ] Image format: `png`
- [ ] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by kolya182** [comment]
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwallet.com/logo-assets). Tokens will show up automatically once the user receives them.
Feel free to share this on social media and tag Trust Wallet:
 Twitter: @trustwalletapp 
Facebook: @trustwalletapp

**Comment by justover** [comment]
Hello Mykola,

Thank you for your answer and for the merge!
I have a question tho, when I search for HighVibe in the trust wallet, I cannot find it. Do you know why?

Thank you in advance,

Nicolas NUPS

**Comment by kolya182** [comment]
Try now

**Comment by justover** [comment]
It is working fine now! Thank you 

Nicolas

**Pull request merged**
