### PR TITLE
Upload CYFM Token

### PR DESCRIPTION
**Pull request by jamestylee**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [ ] Filename in the `lowercase` format
- [ ] Image format: `png`
- [ ] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by vikmeup** [comment]
@jamestylee can you lowercase filename?

**Comment by kolya182** [comment]
Added here https://github.com/TrustWallet/tokens/commit/ea35a2f7d4772021cd28941da35f0e05c37370f9.
@jamestylee 
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwalletapp.com/logo-assets). Tokens will show up automatically once the user receives them.
Feel free to share this on social media and tag Trust Wallet:
 Twitter: @trustwalletapp 
Facebook: @trustwalletapp

**Comment by jamestylee** [comment]
I'm so sorry about that, I didn't even realize the mixed case.   Is it ok to just update this and attach?

Thanks for your logos, absolutely useful for our site and marketing.

-James

0x05d412ce18f24040bb3fa45cf2c69e506586d8e8
0x3f06b5d78406cd97bdf10f5c420b241d32759c80

**Comment by kolya182** [comment]
You already should see it in wallet.

**Comment by jamestylee** [comment]
I did indeed.  Thanks so much!

**Pull request closed without merging**
