### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by Adam-UNV**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [ ] Filename in the `lowercase` format
- [ ] Image format: `png`
- [ ] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by vikmeup** [comment]
@Adam-UNV can you lowercase filename, please?

**Comment by kolya182** [comment]
@Adam-UNV Are you sure it valid contract address ?.

**Comment by Adam-UNV** [comment]
Hi there,

The contract address I submitted in the file name was an ethereum classic
address, as I deployed the token on ETC as a test. Is that supported?

Warm regards,
Adam

**Comment by kolya182** [comment]
@Adam-UNV Oh, sorry i did not check ETC. Yes it supported, but please lowercase address.

**Comment by kolya182** [comment]
Added here https://github.com/TrustWallet/tokens/commit/5d92d8c415adc73007aae63e474c969cd2c13304
@Adam-UNV 
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwalletapp.com/logo-assets). Tokens will show up automatically once the user receives them.
Feel free to share this on social media and tag Trust Wallet:
 Twitter: @trustwalletapp 
Facebook: @trustwalletapp

**Comment by Adam-UNV** [comment]
Great, thanks for that. I'm also having another issue with display of decimals with the ETC token. Can you let me know an email address to send some details?

**Comment by vikmeup** [comment]
@Adam-UNV you can always contact via support@trustwalletapp.com

**Pull request closed without merging**
