### PR TITLE
Upload CrystalCoin

### PR DESCRIPTION
**Pull request by omarhraste**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [ ] Filename in the `lowercase` format
- [ ] Image format: `png`
- [ ] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by kolya182** [comment]
@omarhraste 
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwalletapp.com/logo-assets). Tokens will show up automatically once the user receives them.
Feel free to share this on social media and tag Trust Wallet:
 Twitter: @trustwalletapp 
Facebook: @trustwalletapp

**Comment by kolya182** [comment]
What is your project, can i take a look ?.

**Comment by omarhraste** [comment]
https://www.truegoldcoin.com/ in menu----> Wallet, we are updating the instruction due the last changes in Trust update.

**Comment by omarhraste** [comment]
Dear @kolya182 , in the last Trust´s update, is not possible to export the key? Could be possible?

**Comment by kolya182** [comment]
@omarhraste For multi coin wallet you can export only 12 words, if you have previously imported wallet using Keystore or private key you still can export as Private Key or Keystore.

**Comment by omarhraste** [comment]
@kolya182 , 12 words work only for Trust, i can not import in other wallet (ex: Matamask)

**Comment by kolya182** [comment]
What do you trying import in Metamask ?

**Pull request merged**
