### PR TITLE
upload Bcl Token just now

### PR DESCRIPTION
**Pull request by Dennis8806**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [ ] Filename in the `lowercase` format
- [ ] Image format: `png`
- [ ] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by Dennis8806** [comment]
0xe33eef3ef4796bd9633d5dd8b9e8d500eeb62d2d


for change bcl token

**Comment by vikmeup** [comment]
@Dennis8806 you need to provide contract address of the token

**Comment by Dennis8806** [comment]
@vikmeup may know is like this? thanks

**Comment by kolya182** [comment]
Added here https://github.com/TrustWallet/tokens/commit/cdad25778fad0712b33016fa1894a44531456444
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwalletapp.com/logo-assets). Tokens will show up automatically once the user receives them.
Feel free to share this on social media and tag Trust Wallet:
 Twitter: @trustwalletapp 
Facebook: @trustwalletapp

**Pull request closed without merging**
