### PR TITLE
Upload SDREcoin

### PR DESCRIPTION
**Pull request by MarcoszeLBS**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [ ] Filename in the `lowercase` format
- [ ] Image format: `png`
- [ ] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by vikmeup** [comment]
Can you lowercase filename?

**Comment by MarcoszeLBS** [comment]
yes, need to re upload?

**Comment by vikmeup** [comment]
Yes please, and please delete old one

**Comment by MarcoszeLBS** [comment]
how about the Image Size?

**Comment by MarcoszeLBS** [comment]
OK, will do at once

**Comment by vikmeup** [comment]
It should be 256 by 256

**Comment by MarcoszeLBS** [comment]
Please review and confirm the re-upload SDREcoin image

**Comment by vikmeup** [comment]
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwalletapp.com/logo-assets). Tokens will show up automatically once the user receives them.

Feel free to share this on social media and tag Trust Wallet:
Twitter: @TrustWalletApp
Facebook: @TrustWalletApp

**Pull request merged**
