### PR TITLE
Cryptolympic Torch KMS Dividends Token

### PR DESCRIPTION
**Pull request by owntheday-io**
Run the Cryptolympic Torch on the Blockchain and Earn Dividends for the amount of KMS you run!

### CODE REVIEW

**Comment by vikmeup** [comment]
Can you remove capitalized file?

**Comment by owntheday-io** [comment]
What file is capitalized?  I only added 2 image files, and both are named with the contract address.

Please advise.

- Cerce

**Comment by vikmeup** [comment]
@owntheday-io take a look at requirements: https://github.com/TrustWallet/tokens#requirements, files has to be in lowercase

**Comment by owntheday-io** [comment]
File renamed!  Sorry 'bout that - I overlooked the caps countless times!

**Comment by vikmeup** [comment]
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwalletapp.com/logo-assets). Tokens will show up automatically once the user receives them.

Feel free to share this on social media and tag Trust Wallet:
Twitter: @TrustWalletApp
Facebook: @TrustWalletApp

**Pull request merged**
