### PR TITLE
upload MasonCoin

### PR DESCRIPTION
**Pull request by yesmanenterprises**

### CODE REVIEW

**Comment by kolya182** [comment]
Nice design

**Comment by yesmanenterprises** [comment]
can you please check these two, they don't work

0x743e2916227e10882476da16487e6cf3030df629

0xa4eb64a59adcb1628fedfcf08bb2cced149f8b9b

thank you

**Comment by kolya182** [comment]
Initially you uploaded 0x743e2916227e10882476da16487e6cf3030df629 in uppercase format and on macOS rename files to uppercase doesn't recognized by git. I had have to remove it and upload again. Can you upload again 0xa4eb64a59adcb1628fedfcf08bb2cced149f8b9b

**Comment by kolya182** [comment]
Also try shrink file size without quality lose using https://tinypng.com/

**Pull request merged**
