### PR TITLE
upload bgamelogo

### PR DESCRIPTION
**Pull request by Juddy0839**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [ ] Filename in the `lowercase` format
- [ ] Image format: `png`
- [ ] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by kolya182** [comment]
@Juddy0839 1. Please move to `images` folder 2. To which network this token belongs ?.

**Comment by kolya182** [comment]
Is this contract `0xa47a5e8696b47f1dd612eaad7254c4ca039` Ethereum based ?, cause i can't see it on etherscan

**Comment by Juddy0839** [comment]
Yes, Check it out

https://etherscan.io/address/0xa47a5e8696b47f1dd612eaad7254c4ca03938e9e

Kindly help me add the image...I don't have knowledge about Github.i don't
want to be spamming everything 👍

**Comment by kolya182** [comment]
I see, you were trying to add `0xa47a5e8696b47f1dd612eaad7254c4ca039` which is not  `0xa47a5e8696b47f1dd612eaad7254c4ca03938e9e`. Ok, i have added it for you here https://github.com/TrustWallet/tokens/commit/f136f64a81fadeddf6df592d23789124d93abc5c

**Comment by Juddy0839** [comment]
Thanks 👍

**Pull request closed without merging**
