### PR TITLE
Upload BTEN token

### PR DESCRIPTION
**Pull request by btendeveloper**

### CODE REVIEW

**Comment by btendeveloper** [comment]
We've finished all the processes you guys asked us to do.

Please upload our token image asap 

Thank you

**Comment by vikmeup** [comment]
Can you delete extra file you have attached?

**Comment by btendeveloper** [comment]
hi. i guess i deleted extra file i uploaded. Could you guys check it? Thank you

**Comment by vikmeup** [comment]
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwalletapp.com/logo-assets). Tokens will show up automatically once the user receives them.

Feel free to share this on social media and tag Trust Wallet:
Twitter: @TrustWalletApp
Facebook: @TrustWalletApp

**Pull request merged**
