### PR TITLE
Upload ZEON Network

### PR DESCRIPTION
**Pull request by ZeonNetwork**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [ ] Filename in the `lowercase` format
- [ ] Image format: `png`
- [ ] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by kolya182** [comment]
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwallet.com/logo-assets). Tokens will show up automatically once the user receives them.
Feel free to share this on social media and tag Trust Wallet:
 Twitter: @trustwalletapp 
Facebook: @trustwalletapp

**Comment by ZeonNetwork** [comment]
Why there are no changes in app?

**Comment by ZeonNetwork** [comment]
https://raw.githubusercontent.com/TrustWallet/tokens/master/images/0xe5b826ca2ca02f09c1725e9bd98d9a8874c30532.png

**Comment by kolya182** [comment]
Working just fine, Github has delay serving files

**Comment by ZeonNetwork** [comment]
When does logo appear in app?

**Comment by ZeonNetwork** [comment]
Done, how to rename and delete the logo of an old token https://etherscan.io/token/0xe798ee9b716122463ea6f30198f5659c60bfed4e ?

**Comment by kolya182** [comment]
Normally logo available 5 minutes after PR merged. If you updated the logo it will take some time to see changes with in the app due to cache. If you need update token image 1. Make sure to have fork up to date 2. Or DM me in telegram i will help you

**Pull request merged**
