### PR TITLE
Upload Crypto VENO (VENO) 

### PR DESCRIPTION
**Pull request by CryptoVENO**
Hello friend, I'm upload new logo, please approved request add logo token. 

0x44618de3bf9b6dcbc3750ee058980cb614813d08

### CODE REVIEW

**Comment by CryptoVENO** [comment]
I still not look logo on trust wallet.

**Comment by vikmeup** [comment]
@CryptoVENO it has to be approved first.

**Comment by vikmeup** [comment]
Done! 

https://github.com/TrustWallet/tokens/commit/e64c64963dbc7d14c65059cec1b79e0f5687170b

**Comment by vikmeup** [comment]
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwalletapp.com/logo-assets). Tokens will show up automatically once the user receives them.

Feel free to share this on social media and tag Trust Wallet:
Twitter: @TrustWalletApp
Facebook: @TrustWalletApp

**Comment by CryptoVENO** [comment]
Thank's friends

**Pull request closed without merging**
