### PR TITLE
Add EVT-49B

### PR DESCRIPTION
**Pull request by geastwood**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by kolya182** [comment]
Thanks

**Comment by geastwood** [comment]
Thanks for merging so promptly!

**Comment by kolya182** [comment]
Nice work on this one https://github.com/geastwood/evt-bnb-dex-bridge

**Comment by geastwood** [comment]
Ha, thanks for checking it out. We are keeping adding features to it. 😁

**Comment by kolya182** [comment]
@geastwood Could you contact me in telegram in my bio, i would like to ask you couple of questions regarding a swap.

**Pull request merged**
