### PR TITLE
upload DEATH

### PR DESCRIPTION
**Pull request by foxbit112**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [ ] Filename in the `lowercase` format
- [ ] Image format: `png`
- [ ] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by kolya182** [comment]
Does it have contact address ?

**Comment by foxbit112** [comment]
0xd7eF377E1e124cabC09a6CF01098F0eD6CDCa8DB

**Comment by foxbit112** [comment]
i need help verifying my token its been 3 days of trying to get it to work
now , im exhasted

**Comment by kolya182** [comment]
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwallet.com/logo-assets). Tokens will show up automatically once the user receives them.
Feel free to share this on social media and tag Trust Wallet:
 Twitter: @trustwalletapp 
Facebook: @trustwalletapp

**Pull request merged**
