### PR TITLE
Smaller icon image

### PR DESCRIPTION
**Pull request by chesterbella**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by chesterbella** [comment]
smaller icon image

**Comment by kolya182** [comment]
Make sure to upload only one image to /images folder in lowercase format.
For now added new smaller image here

**Comment by chesterbella** [comment]
> Make sure to upload only one image to /images folder in lowercase format.
> For now added new smaller image here

Oh okay, I thought I did that. Is there anyway to update the picture with the last one I just uploaded?

**Comment by kolya182** [comment]
Added smaller image here https://github.com/TrustWallet/tokens/commit/a1af831f198464de76db0264ade9d222f85e87c8

**Pull request closed without merging**
