### PR TITLE
Add files via upload

### PR DESCRIPTION
**Pull request by OlxaCoin**
we have uploaded our logo 256x256px as requested 0x5925f67d2767d937f47141dac24166b469558222.png

### CODE REVIEW

**Comment by vikmeup** [comment]
Also, you can use this graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwalletapp.com/logo-assets)

**Comment by OlxaCoin** [comment]
ok, we can both shout out on Telegram and Social media that @OlxaCoin #OLXA
OLXA ERC20 Token is live now on @TrustWallet #TrustWallet , Send and
Receive OLXA freely any where  any time using TrustWallet!

Good?

**Comment by vikmeup** [comment]
@OlxaCoin 

@TrustWalletApp - our handle on twitter! Sounds great! Thanks

**Comment by OlxaCoin** [comment]
We have just Followed you on Twitter, and that's our twitter @OlxaCoin
https://twitter.com/OlxaCoin
Once you are ready, we are also ready to boom and boost our campaigns with
our co-operation TrustWalletApp

**Comment by vikmeup** [comment]
We don’t endorse any specific token sale on our social media, but feel free to shoot out to your community!

**Pull request merged**
