### PR TITLE
Upload Discountcoins

### PR DESCRIPTION
**Pull request by billethekid**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [ ] Filename in the `lowercase` format
- [ ] Image format: `png`
- [ ] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by billethekid** [comment]
can you change it yo the last upload image thanks

**Comment by vikmeup** [comment]
@billethekid there is 6 files, can you point me to the right one/

**Comment by billethekid** [comment]
The first was writing DICOUNTCOINS!! 

IT IS: DISCOUNTCOINS 

https://github.com/TrustWallet/tokens/pull/225/commits/194fd2a86108b533ae6cbf50294e99e401619c23 <https://github.com/TrustWallet/tokens/pull/225/commits/194fd2a86108b533ae6cbf50294e99e401619c23> 



De reservering is geplaatst

Kartbaan Winterswijk





Het snelste uitje van de Achterhoek
www.kartbaanwinterswijk.nl
Tel: 0543-533480

**Comment by billethekid** [comment]
the last on i upload

**Comment by billethekid** [comment]
Is it right now ?  

I don’t see any change

**Comment by vikmeup** [comment]
Updated to this image: https://github.com/TrustWallet/tokens/blob/310ec9b219fbbe9be887c2a5273ab66d98ca97a6/images/0x106138d8b7f110e52fe89a9b317ed13d38888db0.png

Because an image already cached, it will take a week until you see updated now.

New users would be seeing new image already

**Comment by billethekid** [comment]
ok thanks

**Comment by billethekid** [comment]
Hello Victor 

Wy is my latest picture not uploaded ? 

Can you check what is going wrong 

It is the last update from yesterday

**Pull request closed without merging**
