### PR TITLE
Upload Massive WAVs

### PR DESCRIPTION
**Pull request by dgvicii**

### CODE REVIEW

**Comment by kolya182** [comment]
@dgvicii Please lowercase contract address and you good to go

**Comment by dgvicii** [comment]
Do I need to upload again or where can I replace with the new file on github

**Comment by dgvicii** [comment]
Ok I have corrected the image text case thank you

**Comment by kolya182** [comment]
Merged for now, but I would recommend to remove the gray border and make background transparent and also adjust the size to `256x256`

**Comment by dgvicii** [comment]
I removed the gray not sure why that was added in my editor, also updated
but I do not see the update as of yet in my wallet

**Pull request merged**
