### PR TITLE
Add iex.ec network token RLC

### PR DESCRIPTION
**Pull request by cherrybomb420**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [ ] Filename in the `lowercase` format
- [ ] Image format: `png`
- [ ] Image size: `256 by 256'
tokens/0xf09209cc5eae846ee2cc4a493e7b962ca7bcfbbb.jpeg

image

### CODE REVIEW

**Comment by kolya182** [comment]
Already added

**Comment by cherrybomb420** [comment]
With the new contract address?

**Comment by kolya182** [comment]
Yes, check image in wallet

**Comment by cherrybomb420** [comment]
How do tokens get the data listed in the wallet also, when i click on the
little thing in the corner it just circles and circles forever. Also i have
other token in my waller that say there is a value on etherscan but not in
the trust wallet app. Can you clarify this for me? I just want to be able
to exchange my tokens for ether then into usd. What are my options?

**Comment by kolya182** [comment]
@cherrybomb420 Can you provide wallet address ?

**Comment by cherrybomb420** [comment]
0x861C9C358Dbd3d2853E634B4324aC70B4B5233CE

**Comment by kolya182** [comment]
Tokens you have do not have value, they have similar names but those are different contract addresses

**Comment by cherrybomb420** [comment]
Okay. What about the tokens in this address, how do i exchange these?
0x6ac150ab9070f74ff7b558ca9d09d65b1ff3b587

**Pull request closed without merging**
