### PR TITLE
Upload Discountcoins

### PR DESCRIPTION
**Pull request by billethekid**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [ ] Filename in the `lowercase` format
- [ ] Image format: `png`
- [ ] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by vikmeup** [comment]
Can you add only relevant images? Thanks

**Comment by billethekid** [comment]
Sorry I have don now how can I remove the wrong image ?

**Comment by billethekid** [comment]
I dont see the picture in my wallet ?

**Comment by vikmeup** [comment]
This needs to be merged first, can you delete unrelated images from this pull request?

**Comment by vikmeup** [comment]
Closed in https://github.com/TrustWallet/tokens/commit/86eb85ee44d5e5573738d1e0b092adc2bb933743

Take a look now

**Comment by billethekid** [comment]
Thanks friend you’re welcome

**Comment by billethekid** [comment]
Holy shit I have made a mistake can you do it fore the last time 

I will upload the right Logo again sorry

**Pull request closed without merging**
