### PR TITLE
Added LUX icon

### PR DESCRIPTION
**Pull request by giaki3003**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by vikmeup** [comment]
@giaki3003 I do not see lux in https://github.com/satoshilabs/slips/blob/master/slip-0044.md

**Comment by giaki3003** [comment]
@vikmeup Indeed, unfortunately the previous dev chose "1" for this BIP, not really sure why, so we'll be transitioning to 3003 in the next release (as seen in master-candidate). Addind to [https://github.com/satoshilabs/slips/blob/master/slip-0044.md](url) in a while too. Let me know if this presents an issue

**Comment by vikmeup** [comment]
@giaki3003 let me know once slip 44 is merged, we will merge it here then.

**Comment by giaki3003** [comment]
> @giaki3003 let me know once slip 44 is merged, we will merge it here then.

Merged

**Pull request merged**
