### PR TITLE
Add BitcoinBlue

### PR DESCRIPTION
**Pull request by flaviosar**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by kolya182** [comment]
Please follow requirements

**Comment by flaviosar** [comment]
> Please follow requirements

What are the requirements?
Tokens are active and functional.

**Comment by kolya182** [comment]
> > Please follow requirements
> 
> What are the requirements?
> Tokens are active and functional.

https://developer.trustwallet.com/add_new_token_image#add-custom-image

**Comment by flaviosar** [comment]
> > > Please follow requirements
> > 
> > 
> > What are the requirements?
> > Tokens are active and functional.
> 
> https://developer.trustwallet.com/add_new_token_image#add-custom-image

I followed the procedure.
I'll try again.
Thank you.

**Comment by flaviosar** [comment]
> > > > Please follow requirements
> > > 
> > > 
> > > What are the requirements?
> > > Tokens are active and functional.
> > 
> > 
> > https://developer.trustwallet.com/add_new_token_image#add-custom-image
> 
> I followed the procedure.
> I'll try again.
> Thank you.

error again.

**Comment by flaviosar** [comment]
> > > Please follow requirements
> > 
> > 
> > What are the requirements?
> > Tokens are active and functional.
> 
> https://developer.trustwallet.com/add_new_token_image#add-custom-image

"0x279a3BCcc607412fD11C6E33d0A3EaF1c16319eE image must be in lowercase"

I send the image in lowercase, and why does it appear that it is in capital letters?

**Comment by kolya182** [comment]
> > > > Please follow requirements
> > > 
> > > 
> > > What are the requirements?
> > > Tokens are active and functional.
> > 
> > 
> > https://developer.trustwallet.com/add_new_token_image#add-custom-image
> 
> "0x279a3BCcc607412fD11C6E33d0A3EaF1c16319eE image must be in lowercase"
> 
> I send the image in lowercase, and why does it appear that it is in capital letters?

You did not remove previously uploaded in uppercase.

**Comment by flaviosar** [comment]
> > > > > Please follow requirements
> > > > 
> > > > 
> > > > What are the requirements?
> > > > Tokens are active and functional.
> > > 
> > > 
> > > https://developer.trustwallet.com/add_new_token_image#add-custom-image
> > 
> > 
> > "0x279a3BCcc607412fD11C6E33d0A3EaF1c16319eE image must be in lowercase"
> > I send the image in lowercase, and why does it appear that it is in capital letters?
> 
> You did not remove previously uploaded in uppercase.

So I need to delete the files I sent so I can send a new one?

**Comment by kolya182** [comment]
> > > > > > Please follow requirements
> > > > > 
> > > > > 
> > > > > What are the requirements?
> > > > > Tokens are active and functional.
> > > > 
> > > > 
> > > > https://developer.trustwallet.com/add_new_token_image#add-custom-image
> > > 
> > > 
> > > "0x279a3BCcc607412fD11C6E33d0A3EaF1c16319eE image must be in lowercase"
> > > I send the image in lowercase, and why does it appear that it is in capital letters?
> > 
> > 
> > You did not remove previously uploaded in uppercase.
> 
> So I need to delete the files I sent so I can send a new one?


You need remove uppercase instances

**Comment by flaviosar** [comment]
> > > > > > > Please follow requirements
> > > > > > 
> > > > > > 
> > > > > > What are the requirements?
> > > > > > Tokens are active and functional.
> > > > > 
> > > > > 
> > > > > https://developer.trustwallet.com/add_new_token_image#add-custom-image
> > > > 
> > > > 
> > > > "0x279a3BCcc607412fD11C6E33d0A3EaF1c16319eE image must be in lowercase"
> > > > I send the image in lowercase, and why does it appear that it is in capital letters?
> > > 
> > > 
> > > You did not remove previously uploaded in uppercase.
> > 
> > 
> > So I need to delete the files I sent so I can send a new one?
> 
> You need remove uppercase instances

How do I do this?
Delete I can not anymore, the previous files?

**Comment by flaviosar** [comment]
> You need remove uppercase instances

"You need remove uppercase instances"
How do I do this?

**Pull request closed without merging**
