### PR TITLE
Upload FQN image

### PR DESCRIPTION
**Pull request by erc20coindev**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by kolya182** [comment]
Image already exist

**Comment by erc20coindev** [comment]
CVA logo is appeared in wallet since yesterday but FQN image is still not attached in Trust wallet

**Comment by kolya182** [comment]
@erc20coindev I was referring to 0x7bb09bc8ade747178e95b1d035ecbeebbb18cfee.png. Please remove it and i will merge.

**Comment by erc20coindev** [comment]
OK,, done

**Comment by erc20coindev** [comment]
it works perfectly now, Thank you

**Pull request merged**
