### PR TITLE
TrueGoldCoin 

### PR DESCRIPTION
**Pull request by echapeta**

### CODE REVIEW

**Comment by vikmeup** [comment]
@echapeta can you lowercase filename? 

Also, you can use this graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwalletapp.com/logo-assets)

**Comment by echapeta** [comment]
Hello Viktor,

We just uploaded a file with lowercased name.

Yes, next week we will include your logo at our webpage (www.TrueGolgCoin.com)

Thank You,


Eduardo G. Chapeta
CEO
Interwave Global

**Comment by echapeta** [comment]
Dear TrustWallet/tokens admin,
My name is Omar Hraste - COO of TruGoldCoin Token.
Recently we have added our logo in a Git fork, for some days we can see our
logo in Trust wallet, but not now.

Our Token Contract Address is:  0xE51601f59A610DAc06868aa711A05e9a4e291256
<https://etherscan.io/address/0xe51601f59a610dac06868aa711a05e9a4e291256>

Attached our (contract.png format) logo.

Could you give us instructions to solve this issue?

Thanks


Omar Hraste
TrueGoldCoin - COO



2018-03-17 10:47 GMT-03:00 Eduardo Chapeta <echapeta@hotmail.com>:

**Comment by echapeta** [comment]
Hello Viktor,


We will like to give free some tokens to a set of addresses.

We have several ways to do it, one is to answer the balanceOf() requests at the token smart contract for new addresses with the free amount.

Will this work with your wallet ?

How you get the token balance for a specific address in order to show it at the wallet ?

Thank You,


Eduardo G. Chapeta
CEO
Interwave Global

**Comment by vikmeup** [comment]
Once you trigger `transfer()` function to send tokens, it will automatically show that token to that user if they are using Trust Wallet, that's where autodetection comes in.

You are able to see the token image now, correct?

**Comment by echapeta** [comment]
Yes, Thank You !


Eduardo G. Chapeta
CEO
Interwave Global

**Pull request merged**
