### PR TITLE
Upload afri

### PR DESCRIPTION
**Pull request by BitUnits**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [ ] Filename in the `lowercase` format
- [ ] Image format: `png`
- [ ] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by kolya182** [comment]
To which network are they belong ?

**Comment by BitUnits** [comment]
Ethereum Classic

**Comment by BitUnits** [comment]
BitUnits.Club project

**Comment by BitUnits** [comment]
Thank you.

**Pull request merged**
