### PR TITLE
Add RYLT to TrustWallet

### PR DESCRIPTION
**Pull request by RoyaltyCOINx**
Contract Address: 0xd30a2e9347ad48ea208ee563a9cdfd80e962a727

Total supply	: 100,000,000,000 RYLT

Token Name	: RoyaltyCOIN
Symbol		: RYLT
Decimals	: 18

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by kolya182** [comment]
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwallet.com/logo-assets). Tokens will show up automatically once the user receives them.
Feel free to share this on social media and tag Trust Wallet:
 Twitter: @trustwalletapp 
Facebook: @trustwalletapp

**Comment by RoyaltyCOINx** [comment]
Thank you,

How do I get put the site on the RoyaltyCOIN.com URL?

Quoting Mykola <notifications@github.com>:

**Comment by kolya182** [comment]
@RoyaltyCOINx I'm not certain on what you asking.

**Comment by RoyaltyCOINx** [comment]
https://independent-group.com/ico/orion/ with different colors.



w
wedowo
Apr 05, 12:32 PM
ReportSpam
Sure, I can change color for your.



Quoting Mykola <notifications@github.com>:

**Comment by kolya182** [comment]
make another PR

**Comment by RoyaltyCOINx** [comment]
Not sure what you mean. I should get a new Public Relations company?


Quoting Mykola <notifications@github.com>:

**Comment by RoyaltyCOINx** [comment]
Hi There,

I would like to give you a tip if you are able to complete the site today.

Is that possible?


Quoting Mykola <notifications@github.com>:

**Pull request merged**
