### PR TITLE
REFER Membership

### PR DESCRIPTION
**Pull request by CryptoRecruit**

### CODE REVIEW

**Comment by vikmeup** [comment]
can you remove ` Token Symbol.jpg` and this should be good to go

**Comment by CryptoRecruit** [comment]
Hey Viktor,

I noticed the last token image uploaded to Trust Wallet wasn't centered. My
fault, didn't have the right sized image according to your walkthrough.

I just reuploaded a better image to GitHub. Does this one work?

Thanks,

Brian

Sent on the go!

Brian Daley
Founder @Smartrefer
647-207-1122
Toronto, Canada

**Comment by vikmeup** [comment]
yeah, just re upload it in the new PR, which ever option works for you

**Comment by CryptoRecruit** [comment]
Great, thanks Viktor!


*Brian Daley*
Founder @ SmartRefer
Toronto, Canada

(647) 207-1122 <(647)%20207-1122>

**Pull request merged**
