### PR TITLE
TrueGoldCoin Icon

### PR DESCRIPTION
**Pull request by echapeta**

### CODE REVIEW

**Comment by vikmeup** [comment]
@echapeta can you lowercase name for the first image?

**Comment by vikmeup** [comment]
You think you just need to have an image for `0xe51601f59a610dac06868aa711a05e9a4e291256` contract only.

**Comment by echapeta** [comment]
Hello Vik, we uploaded the file 0xe51601f59a610dac06868aa711a05e9a4e291256.png , is already in lowercase. We also publiched the Trust app at our website www.truegoldcoin.com

**Comment by echapeta** [comment]
Yes, we need an image only for the 0xe51601f59a610dac06868aa711a05e9a4e291256 contract !

**Comment by vikmeup** [comment]
@echapeta also realized it might be good to make the background transparent for the token, in the case we change backgorund in the app :) 

Would you mind sending few tokens for my collection: `0xe47494379c1d48ee73454c251a6395fdd4f9eb43` ?

**Comment by echapeta** [comment]
Dear Viktor,

We just sent 100 TGC to that address.

Best Regards,


Eduardo G. Chapeta
CEO
Interwave Global

**Comment by vikmeup** [comment]
Received it! Thanks

**Pull request merged**
