### PR TITLE
Update PAX logo

### PR DESCRIPTION
**Pull request by tigersgt**
In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by tigersgt** [comment]
update with a higher quality logo

**Comment by kolya182** [comment]
Image already exist

**Comment by tigersgt** [comment]
Not sure if I did something wrong. I followed the steps and request was closed due to "image already exist".

Please help. Here is the updated image and contract address - 0x8e870d67f660d95d5be530380d0ec0bd388289e1

0x8e870d67f660d95d5be530380d0ec0bd388289e1

**Comment by vikmeup** [comment]
@tigersgt image is updated. Done!

It might be cached on the mobile side for 7 days tho, but new users will see already updated logo.

**Pull request closed without merging**
