### PR TITLE
Upload IZX Token

### PR DESCRIPTION
**Pull request by Alexorro**

### CODE REVIEW

**Comment by vikmeup** [comment]
@Alexorro follow requirements: https://github.com/TrustWallet/tokens#requirements

**Comment by dakson111** [comment]
0x4619df2ca5795834edda178610b6adb46acf47a9

**Comment by kolya182** [comment]
@dakson111 Is this image for contract 0x2ad180cbaffbc97237f572148fc1b283b68d8861 ?

**Comment by dakson111** [comment]
its for SWDC 
0x4619DF2Ca5795834eDdA178610b6aDB46ACF47A9

**Comment by kolya182** [comment]
@dakson111 Added here https://github.com/TrustWallet/tokens/commit/a57db4c6fcd9db641e99ee699692d773d216fb3c

**Pull request merged**
