### PR TITLE
added RIN logo

### PR DESCRIPTION
**Pull request by lavimalik**
Added RIN token
Contract Address: 0xd1508328e81d275e526c215697469c2c060f7ae3
Token Name: RIN
Token Symbol: RIN

In order to streamline the review of the contribution we ask you
to ensure the following steps have been taken:

- [x] Filename in the `lowercase` format
- [x] Image format: `png`
- [x] Image size: `256 by 256 px`

### CODE REVIEW

**Comment by kolya182** [comment]
Also, you can use these graphics to say that your ERC20 token fully compatible with Trust Wallet (https://trustwallet.com/logo-assets). Tokens will show up automatically once the user receives them.
Feel free to share this on social media and tag Trust Wallet:
 Twitter: @trustwalletapp 
Facebook: @trustwalletapp

**Comment by lavimalik** [comment]
For some reason, the contract address had to be changed from 0xd1508328e81d275e526c215697469c2c060f7ae3 to this 0x4bF62424385ddcD858535cAa1878e512314a9Aeb

What can we do to stop the old token from appearing in search?

**Comment by kolya182** [comment]
Do you have a public note of changing contract address, to make sure we do not delist active contract?

**Comment by lavimalik** [comment]
https://twitter.com/ReliableIndex/status/1100109411094274049

Here is the public note

**Comment by kolya182** [comment]
Thank you, we will delist it today.

**Pull request merged**
